# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/admin/Desktop/Uart_Verilog/Genesys2_Master.xdc

# IP: ip/fifo_generator_0/fifo_generator_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet
